services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres-container
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./../scripts/init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql

  mongodb:
    image: mongo
    container_name: mongo-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: transactionsdb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./../scripts/init-mongodb.js:/docker-entrypoint-initdb.d/init-mongodb.js

  wallet-service:
    container_name: wallet-service-container
    build:
      context: ../
      dockerfile: ./docker/dockerfile
    ports:
      - "6000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mongodb
      - postgres

volumes:
  postgres_data:
  mongodb_data:
